package devweb.servlets;

import org.thymeleaf.TemplateEngine;
import org.thymeleaf.context.WebContext;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import java.io.IOException;
import java.io.PrintWriter;

@WebServlet("/guide")
public class GuideServlet extends GenericServlet {

    @Override
    protected void doGet(HttpServletRequest req, HttpServletResponse resp) throws ServletException, IOException {
        resp.setCharacterEncoding("UTF-8");

        PrintWriter out = resp.getWriter();

        out.println("        <!DOCTYPE html>");
        out.println("<html>");
        out.println("");
        out.println("<!-- Titre de l'onglet -->");
        out.println("");
        out.println("                <head>");
        out.println("	<title> Guide Xtrem-Hardware </title>");
        out.println("	<meta charset=\"utf-8\">");
        out.println("	<link rel=\"stylesheet\" type=\"text/css\" href=\"../css/accueil.css\">");
        out.println("	<link rel=\"stylesheet\" type=\"text/css\" href=\"../css/guide.css\">");
        out.println("</head>");
        out.println("");
        out.println("<body>");
        out.println("");
        out.println("<!-- Image titre et option de connexion pour toutes les pages -->");
        out.println("");
        out.println("	<header>");
        out.println("		<div class=\"pcheader\">");
        out.println("			<img src=\"../img/titre.png\">");
        out.println("			<ul class=\"user-nav\">");

        String identifiantUtilisateurConnecte = (String) req.getSession().getAttribute("utilisateurConnecte");
        if (identifiantUtilisateurConnecte==null || "".equals(identifiantUtilisateurConnecte)) {
            out.println("<li><a href=\"../login\"><b>Login</b></a></li>");
            out.println("<li><a href=\"../register\"><b>Register</b></a></li>");
        } else {
            out.println("<li><a href=\"../compte\"><b>Mon Compte</b></a></li>");
            out.println("<li><a href=\"../deconnexion\"><b>Deconnexion</b></a></li>");
        }

        out.println("			</ul>");
        out.println("		</div>");
        out.println("	</header>");
        out.println("");
        out.println("<!-- Barre de navigation identique pour toutes les pages-->");
        out.println("");
        out.println("	<nav class=\"nav\">");
        out.println("		<ul>");
        out.println("			<li><a href=\"accueil\">ACCUEIL</a></li>");
        out.println("			<li><a href=\"guide\">GUIDE DE MONTAGE</a></li>");
        out.println("			<li><a href=\"config\">MA CONFIG</a></li>");
        out.println("			<li><a href=\"photos\">PHOTOS</a></li>");
        out.println("			<li><a href=\"contact\">CONTACT</a></li>");
        out.println("		</ul>");
        out.println("	</nav>");
        out.println("");
        out.println("<!-- Guide avec photos pour le montage d'un pc-->");
        out.println("");
        out.println("                <div class=\"texte\">");
        out.println("		<h1> MONTAGE PC </h1>");
        out.println("");
        out.println("");
        out.println("		<div class=\"bloc1\">");
        out.println("			<p> <b>Comment monter soi-même un ordinateur ? Voici un tutoriel efficace et facile concernant le montage d'un PC.</b></p>");
        out.println("                <p id=\"gauche\"> Vérification du matériel : <p>");
        out.println("				<ul>");
        out.println("					<li> Une carte mère (CM) </li>");
        out.println("					<li> Un processeur (CPU) </li>");
        out.println("					<li> La RAM </li>");
        out.println("					<li> Une alimentation (Alim) </li>");
        out.println("					<li> Une carte graphique (GPU) </li>");
        out.println("					<li> Disque dur et/ou SSD (HDD/SSD/SSHD) </li>");
        out.println("					<li> Un boitier </li>");
        out.println("					<li> Un ventirad </li>");
        out.println("				</ul>");
        out.println("				<img src=\"../img/montage.jpg\"/>");
        out.println("			</div>");
        out.println("");
        out.println("			<div class=\"bloc\">");
        out.println("				<p><b>CONSEILS :</b></p>");
        out.println("				<ul>");
        out.println("					<li> Prévoir une surface de travail assez vaste et plane (Privilégier une table de salle à manger, ou même la surface du sol, mais pas de lit ou de surface molle car vous risquez de perdre la visserie). </li>");
        out.println("					<li> Disposer d'un récipient de type coupelle, bol ou ramequin pour y déposer la visserie complète à chaque étape.</li>");
        out.println("                <li> Utiliser des tournevis cruciformes de petites tailles et de préférence aimantés.</li>");
        out.println("				</ul>");
        out.println("				<img src=\"../img/attention.jpg\"/>");
        out.println("				<p><b>ATTENTION : </b> Les circuits des composants sont très sensibles à l'électricité statique. Dans leur emballage, les cartes mères et cartes graphiques sont entourés d'un plastique anti-statique qui absorbe l'électricité statique, par conséquent ce plastique est riche en électricité statique. Donc il faut éviter de toucher les circuits de ces composants après avoir toucher ce type de plastique ou de mettre en contact direct le plastique avec les composants (de même que les pull en synthétique, ou les cheveux). Pour prévenir tout risque, il vous suffit de vous décharger de votre électricité statique en touchant un objet métallique avant de manipuler les composants (Ex : Parties métalliques du boîtier).</p>");
        out.println("                </div>");
        out.println("");
        out.println("");
        out.println("");
        out.println("			<div class=\"bloc\">");
        out.println("				<h3> 1ère étape -> Mis en place du CPU.</h3>");
        out.println("				<p>Alors dans cette étape vous allez mettre en place le CPU dans son emplacement sur la carte mère. Pour cela, avant tout, regardez la petite flèche au coin inférieur gauche (généralement) à l’emplacement du CPU sur la CM et repérez la même flèche sur le CPU (on appelle ça le \"détrompeur\"). Ouvrez le petit levier et prenez le CPU sur les bords (on va essayer de ne pas toucher le côté doré) et mettez les flèches en concordance, l’une collée à l’autre. Refermez le levier.  </p>");
        out.println("				<img src=\"../img/cpu.jpg\"/>");
        out.println("			</div>");
        out.println("");
        out.println("");
        out.println("			<div class=\"bloc\">");
        out.println("				<h3>2ème étape -> Installer la CM</h3>");
        out.println("				<p>Couchez votre boitier et repérez les trous correspondant au format de votre CM (9 trous pour le format classique ATX). Ouvrez la boite de visserie et prenez le temps de lire le manuel fourni avec le boitier pour repérer les vis nécessaire pour fixer la CM. Fixez ensuite votre CM au fond du boîtier. </p>");
        out.println("				<img src=\"../img/cm.jpg\"/>");
        out.println("			</div>");
        out.println("");
        out.println("");
        out.println("			<div class=\"bloc\">");
        out.println("				<h3>3ème étape -> Remplir la CM </h3>");
        out.println("				<p>Une fois la CM installée, on va donc mettre la RAM, le ventirad et le GPU. Pour la RAM, si vous avez deux barrettes, il faut les installer en dual channel, ce qui veut dire avec un emplacement qui les sépare, référez-vous au manuel de la CM. Enfoncez bien jusqu’à entendre le clic. Faites bien attention, il y a un petit trou sur la barrette de RAM, à faire concorder avec le port.</p>");
        out.println("				<img src=\"../img/composant.jpg\"/>");
        out.println("				<p>Pour le ventirad, placez dans un premier temps la pâte thermique fournie à l'aide de la seringue sous la forme d'une petite noisette au centre du processeur. Repérez les quatre trous autour de l’emplacement du CPU et faites les concorder avec les quatre pieds du ventirad , vissez bien à fond pour éviter les vibrations et les problèmes de surchauffe.</p>");
        out.println("				<img src=\"../img/pate.jpg\"/>");
        out.println("				<p>Enfin le GPU, enlevez le nombre suffisant des petites protections à l’arrière du boitier en fonction de l’emplacement de votre GPU. Collez bien l’arrière du GPU (là où se trouve les sorties vidéo) au boitier, et faite le glisser pour que la carte rentre dans son emplacement. Enfoncez jusqu’à entendre le clic. Vérifiez que la sécurité (à droite du port) est en place et vissez votre GPU au boitier.</p>");
        out.println("			</div>");
        out.println("");
        out.println("");
        out.println("");
        out.println("			<div class=\"bloc\">");
        out.println("				<h3> 4ème étape -> Le stockage et le lecteur CD </h3>");
        out.println("				<p> Repérez la cage pour HHD (en bas), glissez le dedans, avec les connectiques vers l’arrière du boitier, faites de même si vous possédez un SSD. N’hésitez pas à mettre une petite vis pour bien les fixer en plus des fixations facile que possède sans doute votre boitier.</p>");
        out.println("				<img src=\"../img/disque.jpg\"/>");
        out.println("				<p>Pour le lecteur CD, il faut enlever un cache de la face avant de votre boitier, et faites-y glissez votre lecteur jusqu’au fond, rajoutez-y une petite vis (il doit se trouver en haut).</p>");
        out.println("				<img src=\"../img/hdd.jpg\"/>");
        out.println("			</div>");
        out.println("");
        out.println("");
        out.println("");
        out.println("			<div class=\"bloc\">");
        out.println("				<h3>5ème étape -> L’alimentation</h3>");
        out.println("				<p>Placez l’alim à son emplacement (généralement en bas du boitier) avec le ventilateur vers le sol (si votre boîtier comporte une aération en dessous). Passez tous les câbles à l’arrière du boitier.</p>");
        out.println("				<img src=\"../img/alim.png\"/>");
        out.println("				<p>Maintenant toutes les pièces sont à leurs places, il suffit de faire les branchements.</p>");
        out.println("			</div>");
        out.println("");
        out.println("");
        out.println("");
        out.println("			<div class=\"bloc\">");
        out.println("				<h3> 6ème étape -> Les branchements </h3>");
        out.println("				<p> Voici l’étape sans doute la plus longue si vous voulez un beau câble management et que tout démarre ensuite. Prenez votre temps pour cette étape et référez vous toujours au manuel de la CM.</p>");
        out.println("				<p>On va déjà brancher la CM avec l’alim, pour cela, repérez le plus gros câbles de l’alim et branchez le à la CM (l’emplacement est généralement a droite). Repérez un autre câble, généralement 2x4 broches (sur lequel doit être marqué CPU) et branchez le (généralement en haut à gauche) sur la CM.</p>");
        out.println("				<img src=\"../img/branchement.jpg\" />");
        out.println("				<p>Le ventirad possède un ventilo, branchez le donc à l’emplacement « CPU fan » (généralement en haut du ventirad ). Référez vous bien aux schémas du manuel de la carte mère, pour connaître plus facilement les emplacements.</p>");
        out.println("				<p>Le stockage et le lecteur CD ont les mêmes connectiques, prenez les câbles SATA fournis avec la CM, branchez les à la CM « SATA 1/2/3/… » (généralement sur la droite) et aux lecteurs CD/HHD. Trouvez dans les câbles de l’alim des connectiques en forme de  « L ». Branchez les aux périphérique de stockage.</p>");
        out.println("				<p>Le GPU : Trouvez des connectiques 6 ou 8 broches sur l’alim (vous aurez sans doute besoin de deux câbles) et branchez bien deux câbles si vous possédez 2x6 ou 6+8 sur votre GPU.</p>");
        out.println("				<p>Le boitier : Pour les ventilos du boitier, trouvez sur la CM les « sys fan», branchez y les ventilos. Vous avez sans doute aussi un gros câble bleu venant du boiter, c’est l’USB, branchez le à son emplacement(généralement bleu aussi sur la droite de la CM). De même si vous possédez des port usb, branchez les à leurs emplacements (généralement plus en bas de la CM). Pour les câbles audio, les connectiques doivent se trouver aussi en bas de la CM. Il reste plus qu’une petite série de câble (le front panel), lisez très attentivement le manuel de votre CM pour branchez ceux-là, il y a un emplacement très précis pour chaque pins (les emplacement doivent se trouver en bas de la CM).</p>");
        out.println("			</div>");
        out.println("");
        out.println("			<div class=\"bloc\">");
        out.println("				<h3> 7ème étape -> Installation de Windows </h3>");
        out.println("				<p>Nous y voilà ! Nos composants que nous avons mis tant de temps à choisir, dont nous avons attendu impatiemment la livraison et que nous avons assemblé avec amour forment enfin un tout prêt à être utilisé. C'est beau, c'est émouvant ! Mais ce n'est pas tout à fait fini… Il manque un élément essentiel à notre configuration : l'OS.</p>");
        out.println("				<img src=\"../img/windows.png\" />");
        out.println("				<p> Dans un premier temps, réaliser une clé USB bootable de Windows grâce à un fichier ISO que vous pourrez téléchager directement sur microsoft.fr et veillez à bien prendre une version 64 bits. </p>");
        out.println("				<p> Il faut ensuite grâce au manuel d'utilisation de votre carte mère, changez l'ordre de BOOT pour lancer la clé USB au démarrage de l'ordinateur. Ensuite redémarrez. La fênetre d'installation de Windows va alors apparaître, laissez vous guidez. L'installation met plus au moins de temps selon si vous avez un SSD ou non mais comptez environ 30min.");
        out.println("        Voilà vous pouvez à présent profitez de votre ordinateur monté par vos propre soin. Pensez à en prendre soin et à le nettoyer régulierement. Merci d'avoir suivi ce guide. </p>");
        out.println("");
        out.println("                </div>");
        out.println("	</div>");
        out.println("	</body>");
        out.println("");
        out.println("<!-- Barre de bas de page identique pour toutes les pages -->");
        out.println("");
        out.println("		<footer>");
        out.println("			<div class=\"bas-page\">");
        out.println("");
        out.println("				<ul class=\"footer-nav\">");
        out.println("					<h4>Sections</h4>");
        out.println("					<li><a href=\"../accueil\">Accueil</a></li>");
        out.println("					<li><a href=\"../guide\">Guide de Montage</a></li>");
        out.println("					<li><a href=\"../config\">Configuration</a></li>");
        out.println("					<li><a href=\"../photos\">Album Photos</a></li>");
        out.println("				</ul>");
        out.println("");
        out.println("				<ul class=\"footer-nav\">");
        out.println("					<h4> A Propos</h4>");
        out.println("					<li><a href=\"../accueil\">About</a></li>");
        out.println("					<li><a href=\"../contact\">Contact </a></li>");
        out.println("				</ul>");
        out.println("");
        out.println("				<ul class=\"footer-nav\">");
        out.println("					<h4>Rejoins Nous </h4>");
        out.println("					<li><a href=\"https://www.facebook.com\">Facebook</a></li>");
        out.println("					<li><a href=\"https://instagram.com\">Instagram</a></li>");
        out.println("					<li><a href=\"https://twitter.com\">Twitter</a></li>");
        out.println("					<li><a href=\"https://www.youtube.com\">YouTube</a></li>");
        out.println("				</ul>");
        out.println("");
        out.println("				<div class=\"footer-branding\">");
        out.println("					<div class=\"copyright-notice\">2017 Xtrem Hardware.  All rights reserved.</div>");
        out.println("				</div>");
        out.println("");
        out.println("			</div>");
        out.println("			</footer>");
        out.println("		</html>");
    }
}

