package devweb.servlets;


import org.thymeleaf.TemplateEngine;
import org.thymeleaf.context.WebContext;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import java.io.IOException;
import java.io.PrintWriter;

@WebServlet("/photos")
public class PhotosServlet extends GenericServlet {

    @Override
    protected void doGet(HttpServletRequest req, HttpServletResponse resp) throws ServletException, IOException {
        resp.setCharacterEncoding("UTF-8");
        PrintWriter out = resp.getWriter();

        out.println("        <!DOCTYPE html>");
        out.println("<html>");
        out.println("");
        out.println("<!-- Titre de l'onglet -->");
        out.println("");
        out.println("                <head>");
        out.println("	<title> Photos Xtrem-Hardware </title>");
        out.println("	<meta charset=\"utf-8\">");
        out.println("	<link rel=\"stylesheet\" type=\"text/css\" href=\"../css/accueil.css\">");
        out.println("</head>");
        out.println("");
        out.println("");
        out.println("<body>");
        out.println("");
        out.println("<!-- Image titre et option de connexion pour toutes les pages -->");
        out.println("");
        out.println("	<header>");
        out.println("		<div class=\"pcheader\">");
        out.println("			<img src=\"../img/titre.png\">");
        out.println("			<ul class=\"user-nav\">");

        String identifiantUtilisateurConnecte = (String) req.getSession().getAttribute("utilisateurConnecte");
        if (identifiantUtilisateurConnecte==null || "".equals(identifiantUtilisateurConnecte)) {
            out.println("<li><a href=\"../login\"><b>Login</b></a></li>");
            out.println("<li><a href=\"../register\"><b>Register</b></a></li>");
        } else {
            out.println("<li><a href=\"../compte\"><b>Mon Compte</b></a></li>");
            out.println("<li><a href=\"../deconnexion\"><b>Deconnexion</b></a></li>");
        }

        out.println("			</ul>");
        out.println("		</div>");
        out.println("	</header>");
        out.println("");
        out.println("<!-- Barre de navigation identique pour toutes les pages-->");
        out.println("");
        out.println("	<nav class=\"nav\">");
        out.println("		<ul>");
        out.println("			<li><a href=\"accueil\">ACCUEIL</a></li>");
        out.println("			<li><a href=\"guide\">GUIDE DE MONTAGE</a></li>");
        out.println("			<li><a href=\"config\">MA CONFIG</a></li>");
        out.println("			<li><a href=\"photos\">PHOTOS</a></li>");
        out.println("			<li><a href=\"contact\">CONTACT</a></li>");
        out.println("		</ul>");
        out.println("	</nav>");
        out.println("");
        out.println("");
        out.println("<!-- Affichage des images avec zoom lors du click sur fond noir -->");
        out.println("");
        out.println("");
        out.println("	<h1> NOS MEILLEURES REALISATIONS </h1>");
        out.println("</br>");
        out.println("	<div class=\"photos\">");
        out.println("");
        out.println("		<a href = \"javascript:void(0)\" onclick = \"document.getElementById('light').style.display='block';document.getElementById('fade').style.display='block'\">");
        out.println("			<img src=\"../img/mod1.jpg\"/>");
        out.println("		</a>");
        out.println("		<div id=\"light\" class=\"white_content\">");
        out.println("			<img id=\"zoom\" src=\"../img/mod1.jpg\"/>");
        out.println("			<a href = \"javascript:void(0)\" onclick = \"document.getElementById('light').style.display='none';document.getElementById('fade').style.display='none'\">Close</a>");
        out.println("		</div>");
        out.println("		");
        out.println("");
        out.println("");
        out.println("		<a href = \"javascript:void(0)\" onclick = \"document.getElementById('light1').style.display='block';document.getElementById('fade').style.display='block'\">");
        out.println("			<img src=\"../img/mod2.jpg\"/>");
        out.println("		</a>");
        out.println("		<div id=\"light1\" class=\"white_content\">");
        out.println("			<img id=\"zoom\" src=\"../img/mod2.jpg\"/>");
        out.println("			<a href = \"javascript:void(0)\" onclick = \"document.getElementById('light1').style.display='none';document.getElementById('fade').style.display='none'\">Close</a>");
        out.println("		</div>");
        out.println("");
        out.println("");
        out.println("");
        out.println("		<a href = \"javascript:void(0)\" onclick = \"document.getElementById('light2').style.display='block';document.getElementById('fade').style.display='block'\">");
        out.println("			<img src=\"../img/mod3.jpg\"/>");
        out.println("		</a>");
        out.println("		<div id=\"light2\" class=\"white_content\">");
        out.println("			<img id=\"zoom\" src=\"../img/mod3.jpg\"/>");
        out.println("			<a href = \"javascript:void(0)\" onclick = \"document.getElementById('light2').style.display='none';document.getElementById('fade').style.display='none'\">Close</a>");
        out.println("		</div>");
        out.println("");
        out.println("");
        out.println("");
        out.println("		<a href = \"javascript:void(0)\" onclick = \"document.getElementById('light3').style.display='block';document.getElementById('fade').style.display='block'\">");
        out.println("			<img src=\"../img/mod4.jpg\"/>");
        out.println("		</a>");
        out.println("		<div id=\"light3\" class=\"white_content\">");
        out.println("			<img id=\"zoom\" src=\"../img/mod4.jpg\"/>");
        out.println("			<a href = \"javascript:void(0)\" onclick = \"document.getElementById('light3').style.display='none';document.getElementById('fade').style.display='none'\">Close</a>");
        out.println("		</div>");
        out.println("");
        out.println("");
        out.println("");
        out.println("		<a href = \"javascript:void(0)\" onclick = \"document.getElementById('light4').style.display='block';document.getElementById('fade').style.display='block'\">");
        out.println("			<img src=\"../img/mod5.jpg\"/>");
        out.println("		</a>");
        out.println("		<div id=\"light4\" class=\"white_content\">");
        out.println("			<img id=\"zoom\" src=\"../img/mod5.jpg\"/>");
        out.println("			<a href = \"javascript:void(0)\" onclick = \"document.getElementById('light4').style.display='none';document.getElementById('fade').style.display='none'\">Close</a>");
        out.println("		</div>");
        out.println("");
        out.println("");
        out.println("");
        out.println("		<a href = \"javascript:void(0)\" onclick = \"document.getElementById('light5').style.display='block';document.getElementById('fade').style.display='block'\">");
                out.println("			<img src=\"../img/mod6.jpg\"/>");
        out.println("		</a>");
        out.println("		<div id=\"light5\" class=\"white_content\">");
        out.println("			<img id=\"zoom\" src=\"../img/mod6.jpg\"/>");
        out.println("			<a href = \"javascript:void(0)\" onclick = \"document.getElementById('light5').style.display='none';document.getElementById('fade').style.display='none'\">Close</a>");
        out.println("		</div>");
        out.println("");
        out.println("");
        out.println("");
        out.println("		<a href = \"javascript:void(0)\" onclick = \"document.getElementById('light6').style.display='block';document.getElementById('fade').style.display='block'\">");
        out.println("			<img src=\"../img/mod7.jpg\"/>");
        out.println("		</a>");
        out.println("		<div id=\"light6\" class=\"white_content\">");
        out.println("			<img id=\"zoom\" src=\"../img/mod7.jpg\" width=\"700\"/>");
        out.println("			<a href = \"javascript:void(0)\" onclick = \"document.getElementById('light6').style.display='none';document.getElementById('fade').style.display='none'\">Close</a>");
        out.println("		</div>");
        out.println("");
        out.println("");
        out.println("");
        out.println("		<a href = \"javascript:void(0)\" onclick = \"document.getElementById('light7').style.display='block';document.getElementById('fade').style.display='block'\">");
        out.println("			<img src=\"../img/mod8.jpg\"/>");
        out.println("		</a>");
        out.println("		<div id=\"light7\" class=\"white_content\">");
        out.println("			<img id=\"zoom\" src=\"../img/mod8.jpg\" width=\"700\"/>");
        out.println("			<a href = \"javascript:void(0)\" onclick = \"document.getElementById('light7').style.display='none';document.getElementById('fade').style.display='none'\">Close</a>");
        out.println("		</div>");
        out.println("");
        out.println("");
        out.println("");
        out.println("		<a href = \"javascript:void(0)\" onclick = \"document.getElementById('light8').style.display='block';document.getElementById('fade').style.display='block'\">");
        out.println("			<img src=\"../img/mod9.jpg\"/>");
        out.println("		</a>");
        out.println("		<div id=\"light8\" class=\"white_content\">");
        out.println("			<img id=\"zoom\" src=\"../img/mod9.jpg\" width=\"700\"/>");
        out.println("			<a href = \"javascript:void(0)\" onclick = \"document.getElementById('light8').style.display='none';document.getElementById('fade').style.display='none'\">Close</a>");
        out.println("		</div>");
        out.println("");
        out.println("");
        out.println("");
        out.println("		<a href = \"javascript:void(0)\" onclick = \"document.getElementById('light9').style.display='block';document.getElementById('fade').style.display='block'\">");
        out.println("			<img src=\"../img/mod10.jpg\"/>");
        out.println("		</a>");
        out.println("		<div id=\"light9\" class=\"white_content\">");
        out.println("			<img id=\"zoom\" src=\"../img/mod10.jpg\" width=\"700\" />");
        out.println("			<a href = \"javascript:void(0)\" onclick = \"document.getElementById('light9').style.display='none';document.getElementById('fade').style.display='none'\">Close</a>");
        out.println("		</div>");
        out.println("");
        out.println("");
        out.println("");
        out.println("		<a href = \"javascript:void(0)\" onclick = \"document.getElementById('light10').style.display='block';document.getElementById('fade').style.display='block'\">");
        out.println("			<img src=\"../img/mod11.jpg\"/>");
        out.println("		</a>");
        out.println("		<div id=\"light10\" class=\"white_content\">");
        out.println("			<img id=\"zoom\" src=\"../img/mod11.jpg\" width=\"700\"/>");
        out.println("			<a href = \"javascript:void(0)\" onclick = \"document.getElementById('light10').style.display='none';document.getElementById('fade').style.display='none'\">Close</a>");
        out.println("		</div>");
        out.println("");
        out.println("");
        out.println("");
        out.println("		<a href = \"javascript:void(0)\" onclick = \"document.getElementById('light11').style.display='block';document.getElementById('fade').style.display='block'\">");
        out.println("			<img src=\"../img/mod12.jpg\"/>");
        out.println("		</a>");
        out.println("		<div id=\"light11\" class=\"white_content\">");
        out.println("			<img id=\"zoom\" src=\"../img/mod12.jpg\" width=\"700\"/>");
        out.println("			<a href = \"javascript:void(0)\" onclick = \"document.getElementById('light11').style.display='none';document.getElementById('fade').style.display='none'\">Close</a>");
        out.println("		</div>");
        out.println("		<div id=\"fade\" class=\"black_overlay\"></div>");
        out.println("");
        out.println("	</div>");
        out.println("");
        out.println("");
        out.println("<!-- Barre de bas de page identique pour toutes les pages -->");
        out.println("");
        out.println("		<footer>");
        out.println("			<div class=\"bas-page\">");
        out.println("");
        out.println("				<ul class=\"footer-nav\">");
        out.println("					<h4>Sections</h4>");
        out.println("					<li><a href=\"../accueil\">Accueil</a></li>");
        out.println("					<li><a href=\"../guide\">Guide de Montage</a></li>");
        out.println("					<li><a href=\"../config\">Configuration</a></li>");
        out.println("					<li><a href=\"../photos\">Album Photos</a></li>");
        out.println("				</ul>");
        out.println("");
        out.println("				<ul class=\"footer-nav\">");
        out.println("					<h4> A Propos</h4>");
        out.println("					<li><a href=\"../accueil\">About</a></li>");
        out.println("					<li><a href=\"../contact\">Contact </a></li>");
        out.println("				</ul>");
        out.println("");
        out.println("				<ul class=\"footer-nav\">");
        out.println("					<h4>Rejoins Nous </h4>");
        out.println("					<li><a href=\"https://www.facebook.com\">Facebook</a></li>");
        out.println("					<li><a href=\"https://instagram.com\">Instagram</a></li>");
        out.println("					<li><a href=\"https://twitter.com\">Twitter</a></li>");
        out.println("					<li><a href=\"https://www.youtube.com\">YouTube</a></li>");
        out.println("				</ul>");
        out.println("");
        out.println("				<div class=\"footer-branding\">");
        out.println("					<div class=\"copyright-notice\">2017 Xtrem Hardware.  All rights reserved.</div>");
        out.println("				</div>");
        out.println("");
        out.println("");
        out.println("			</footer>");
        out.println("");
        out.println("		</html>");



    }
}

