
CREATE DATABASE base

CREATE TABLE `MEMBRE` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(42) NOT NULL,
  `mdp` VARCHAR(42) NOT NULL,
  `pseudo` VARCHAR(42) NOT NULL,
  `email` VARCHAR(42) NOT NULL,
  PRIMARY KEY (`id`)
)
